#!/bin/bash

set -e

PACKAGES_TO_INSTALL=(
  gh                       # Github CLI
  distrobox                # Distrobox
  libappindicator-gtk3     # Gnome Shell extension for tray icons
  mozilla-https-everywhere # HTTPS enforcement extension for Mozilla Firefox
  podman-compose
  zsh
  fira-code-fonts          # Font
  solaar                   # Logitech keyboard
  solaar-udev              # Logitech keyboard
)

is_installed() {
  local cmd="$1"
  command -v "$cmd" &>/dev/null
}

echo "🔧 Setting up your Silverbue from scratch..."
echo "Install packages..."
MISSING_PACKAGES=()
for pkg in "${PACKAGES_TO_INSTALL[@]}"; do
  if ! rpm -q "$pkg" &>/dev/null; then
    MISSING_PACKAGES+=("$pkg")
  fi
done
if [ ${#MISSING_PACKAGES[@]} -ne 0 ]; then
  rpm-ostree install -y "${MISSING_PACKAGES[@]}" && reboot
else
  echo "All packages are already installed. Skipping rpm-ostree install."
fi

## InitramFS
! rpm-ostree status -b | grep -q "Initramfs: regenerate" && (
  echo "Enable initramfs..." && \
  rpm-ostree initramfs --enable 2> /dev/null && \
  reboot \
) || echo "Initramfs already enabled"

# Github
gh auth status 2>&1 | grep -q "not logged into"  && (
  echo "Login to Github" && \
  gh auth login \
) || echo "Already logged into Github"

## Fonts
FONT_DIR=${HOME}/.local/share/fonts
mkdir -p $FONT_DIR
declare -A FONTS=(
  ["MesloLGS NF Regular.ttf"]="https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
  ["MesloLGS NF Bold.ttf"]="https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
  ["MesloLGS NF Italic.ttf"]="https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
  ["MesloLGS NF Bold Italic.ttf"]="https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
)
for FONT_NAME in "${!FONTS[@]}"; do 
  FONT_URL="${FONTS[$FONT_NAME]}"
  DEST="${FONT_DIR}/${FONT_NAME}"
  ! test -f "$DEST" && (
    echo "Install font $FONT_NAME..." && \
    curl -fsSL ${FONT_URL} -o "${DEST}" \
  ) || echo "Font $DEST already installed"
done

echo "🎉 Setup complete!"
